# ASP.NET Core 

# Build and test ASP.NET Core projects targeting .NET Core. 

# Add steps that run tests, create a NuGet package, deploy, and more: 

# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnetcore 

 

trigger: 

- master 

 

pool: 

  vmImage: ubuntu-latest 

 

variables: 

  buildConfiguration: 'Main' 

 

stages: 

- stage: Build 

  displayName: 'Build Stage' 

  jobs: 

  - job: BuildJob 

    displayName: 'Build Job' 

    steps: 

    - script: | 

        echo "Restoring project dependencies..." 

      displayName: 'Restore dependencies' 

    - script: dotnet build --configuration $(buildConfiguration) 

      displayName: 'dotnet build $(buildConfiguration)' 

    - script: | 

        echo "Running unit tests..." 

      displayName: 'Run unit tests' 

 

- stage: Test 

  displayName: 'Test Stage' 

  dependsOn: Build 

  isSkippable: false 

  jobs: 

  - job: TestJob 

    displayName: 'Test Job' 

    steps: 

    - script: | 

        echo "Running unit tests..." 

      displayName: 'Run unit tests' 